[build]
  command = "pnpm run build"
  publish = "dist/pokemon--ssr/browser"

[[redirects]]
  from = "/"
  to = "/about"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200
